#!/usr/bin/env python3
"""Cross-platform framework-integrity and optional live-agent release gate."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]


def run(label: str, command: Sequence[str]) -> None:
    print(f"== {label} ==", flush=True)
    completed = subprocess.run(list(command), cwd=ROOT, check=False)
    if completed.returncode != 0:
        raise SystemExit(f"{label} failed with exit code {completed.returncode}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validate contracts, eval harness, and optionally a produced LIVE_AGENT result."
    )
    parser.add_argument(
        "--live-results",
        type=Path,
        help="Optional eval-results.v2 generated by a live producer; enables the release gate.",
    )
    parser.add_argument("--report", type=Path, help="Optional report path for the live gate")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    python = sys.executable
    run(
        "Agent instruction sources",
        [python, "scripts/validate_agent_instruction_sources.py"],
    )
    run("Schema contracts", [python, "scripts/test_schemas.py"])
    run("Strategy reconstruction", [python, "scripts/test_strategy_reconstruction.py"])
    run("Strategy concept audit", [python, "scripts/test_strategy_concept_audit.py"])
    run("Condition inquiry", [python, "scripts/test_condition_inquiry.py"])
    run(
        "Bounded quantitative data analysis",
        [python, "scripts/test_data_analysis_report.py"],
    )
    run(
        "Causal-identification review",
        [python, "scripts/test_causal_identification.py"],
    )
    run(
        "Scientific-philosophy review",
        [python, "scripts/test_scientific_philosophy_review.py"],
    )
    run(
        "Framework-control review",
        [python, "scripts/test_framework_control_review.py"],
    )
    run(
        "Workflow problem records",
        [python, "scripts/test_problem_record.py"],
    )
    run(
        "Specialist capability discovery",
        [python, "scripts/test_specialist_capability_check.py"],
    )
    run(
        "Scientific skill capability manifest",
        [python, "scripts/test_scientific_skill_manifest.py"],
    )
    run(
        "Outcome evidence contract",
        [python, "scripts/test_outcome_evidence_contract.py"],
    )
    run(
        "Pipeline integrity assessment",
        [python, "scripts/test_pipeline_integrity_assessment.py"],
    )
    run("Executed validation and controls", [python, "scripts/test_execution_controls.py"])
    run(
        "Research orchestration",
        [python, "scripts/test_research_orchestration.py"],
    )
    run("Entry thresholds", [python, "scripts/test_entry_thresholds.py"])
    run("Hypothesis generator", [python, "scripts/test_generator.py"])
    run("Backend contracts (no engine execution)", [python, "scripts/test_backends.py"])
    run("Eval protocol smoke", [python, "evals/run_evals.py"])
    run(
        "Eval unit and producer integration tests",
        [python, "-m", "unittest", "discover", "-s", "evals/tests", "-v"],
    )
    if args.live_results:
        command = [
            python,
            "evals/run_evals.py",
            "--results",
            str(args.live_results),
            "--require-run-kind",
            "LIVE_AGENT",
            "--verbose",
        ]
        if args.report:
            command.extend(["--report", str(args.report)])
        run("Live-agent release gate", command)
        print("Framework integrity and LIVE_AGENT release gate passed.")
    else:
        print(
            "Framework integrity passed. LIVE_AGENT release gate was NOT run; "
            "provide --live-results to make a model/prompt release claim."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
